# Generated by Django 5.1.3 on 2024-11-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_author_mongo_id_alter_author_born_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='mongo_id',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
