# Generated by Django 5.1.3 on 2024-11-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_author_mongo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='added_by',
        ),
        migrations.AddField(
            model_name='quote',
            name='mongo_id',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.CharField(max_length=200),
        ),
    ]
